version: '3'
services:
  horizon-game-server:
    build:
      context: .
      target: final
      dockerfile: Dockerfile.rust
    ports:
      - 3000:3000

  horizon-memory-db:
    build:
      context: .
      dockerfile: Dockerfile.golang
    restart: always
    depends_on:
      - horizon-game-server

  horizon-physics-engine:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    depends_on:
      - horizon-memory-db