services:
  horizon-game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - RUST_LOG=info
    networks:
      - horizon-network

volumes:
  memory-db-data:

networks:
  horizon-network:
    driver: bridge
